docs: 0292的手动更新
Switched to a new branch '292'
https://github.com/LetMeFly666/LeetCode/issues/211

请编辑题解: “Solutions/LeetCode 0292.Nim游戏.md”，注意不要更改文件前5行
请去掉可能的由其他插件自动生成的头部注释信息，并保存你所编辑的题解
请输入CSDN题解文章的id(11022152)：136024724
请重新复制所有的题解内容，并粘贴到CSDN中发布
请在LeetCode中新建、编辑并发布题解
LeetCode题解的url: https://leetcode.cn/problems/nim-game/solutions/2631098/letmefly-292nim-you-xi-nao-jin-ji-zhuan-z34go/
38 533
Traceback (most recent call last):
  File "F:\OtherApps\Program\Git\Store\Store20_LeetCode\newSolution.py", line 152, in <module>
    readme = readmeNewLine(readme)
  File "F:\OtherApps\Program\Git\Store\Store20_LeetCode\newSolution.py", line 149, in readmeNewLine
    splited.insert(i, generateNewLine())
  File "F:\OtherApps\Program\Git\Store\Store20_LeetCode\newSolution.py", line 148, in generateNewLine
    return """|{0:04d}.{1}|{2}|<a href="{3}" target="_blank">题目地址</a>|<a href="{4}" target="_blank">题解地址</a>|<a href="https://letmefly.blog.csdn.net/article/details/{5}" target="_blank">CSDN题 ils/{5}" target="_blank">CSDN题解</a>|<a href="{6}" target="_blank">LeetCode题解</a>|""".format(num, title, getHard(), getProblemUrl(), solutionURLll, csdnid, solutionURLlc)
  File "F:\OtherApps\Program\Git\Store\Store20_LeetCode\newSolution.py", line 131, in getHard
    realTags = tags.split("tags: [")[1][:-1].split(", ")
IndexError: list index out of range