2561: AC.go+CE.java (#1059)
go - AC,36.54%,26.25%

Line 17: error: method merge in interface Map<K,V> cannot be applied to given types;
            timeDiffs.merge(1, Integer::sum);
                     ^
  required: Integer,Integer,BiFunction<? super Integer,? super Integer,? extends Integer>
  found:    int,Integer::sum
  reason: actual and formal argument lists differ in length
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
Line 17: error: incompatible types: Integer is not a functional interface
            timeDiffs.merge(1, Integer::sum);
                               ^
Line 21: error: method merge in interface Map<K,V> cannot be applied to given types;
            timeDiffs.merge(-1, Integer::sum);
                     ^
  required: Integer,Integer,BiFunction<? super Integer,? super Integer,? extends Integer>
  found:    int,Integer::sum
  reason: actual and formal argument lists differ in length
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
Line 21: error: incompatible types: Integer is not a functional interface
            timeDiffs.merge(-1, Integer::sum);
                                ^
Line 39: error: method sort in interface List<E> cannot be applied to given types;
        change.sort();
              ^
  required: Comparator<? super Integer>
  found:    no arguments
  reason: actual and formal argument lists differ in length
  where E is a type-variable:
    E extends Object declared in interface List
5 errors