fix: update node version in .yml
https://github.com/LetMeFly666/LeetCode/actions/runs/12684093364/job/35352233122

14 packages are looking for funding
  run `npm fund` for details
  INFO  Cloning hexo-starter https://github.com/hexojs/hexo-starter.git
  INFO  Install dependencies
  warning hexo > warehouse > cuid@2.1.8: Cuid and other k-sortable and
  non-cryptographic ids (Ulid, ObjectId, KSUID, all UUIDs) are all
  insecure. Use @paralleldrive/cuid2 instead.
  warning hexo-renderer-stylus > stylus > glob@7.2.3: Glob versions
  prior to v9 are no longer supported
  warning hexo-renderer-stylus > stylus > glob > inflight@1.0.6: This
  module is not supported, and leaks memory. Do not use it. Check out
  lru-cache if you want a good and tested way to coalesce async requests
  by a key value, which is much more comprehensive and powerful.
  error lru-cache@11.0.2: The engine "node" is incompatible with this
  module. Expected version "20 || >=22". Got "18.20.5"
  error Found incompatible module.
  WARN  Failed to install dependencies. Please run 'npm install' in
  "/home/runner/work/LeetCode/hexoWorkspace" folder.
  sed: can't read ../hexoWorkspace/node_modules/marked/lib/*: No such
  file or directory
  Error: Process completed with exit code 2.

Signed-off-by: LetMeFly666 <814114971@qq.com>