update: 添加问题“2138.将字符串拆分为若干长度为k的组”的代码和题解(#994)
* archive: MGJW

Signed-off-by: LetMeFly666 <814114971@qq.com>

* archive: last week 组会时

Signed-off-by: LetMeFly666 <814114971@qq.com>

* merge: folder name

Signed-off-by: LetMeFly666 <814114971@qq.com>

* archive: 不好用，先整其他的了

Signed-off-by: LetMeFly666 <814114971@qq.com>

* fix: resolve unsafe port

Signed-off-by: LetMeFly666 <814114971@qq.com>

* unai: 去AI话 - 写的代码一股AI味儿

Signed-off-by: LetMeFly666 <814114971@qq.com>

* archive: from flask import Flask, render_template, request, redirect, url_for
ImportError: cannot import name 'Flask' from partially initialized module 'flask' (most likely due to a circular import) (/Users/bytedance/Library/Python/3.9/lib/python/site-packages/flask/__init__.py)

Signed-off-by: LetMeFly666 <814114971@qq.com>

* archive: 开组会去

Signed-off-by: LetMeFly666 <814114971@qq.com>

* archive: 不应该在owa下ga .

Signed-off-by: LetMeFly666 <814114971@qq.com>

* rename: 还没rename到thisWeek就要rename到lastWeek/14了

Signed-off-by: LetMeFly666 <814114971@qq.com>

* rename: 这个才是toRenameToThisWeek

Signed-off-by: LetMeFly666 <814114971@qq.com>

* 2138: AC.cpp+py+go + WA.java (#993)

go - AC,100.00%,81.82%

Signed-off-by: LetMeFly666 <814114971@qq.com>

* 2138: AC.cpp+py+go + WA.java (#993)

java - AC,83.64%,72.73%

Signed-off-by: LetMeFly666 <814114971@qq.com>

* archive: 这些吐槽当没看见好了

Signed-off-by: LetMeFly666 <814114971@qq.com>

* docs: 域名备案+题解

Signed-off-by: LetMeFly666 <814114971@qq.com>

* docs: 刚就收到回复了 - 2025年6月23日（星期一）下午1 : 37

Signed-off-by: LetMeFly666 <814114971@qq.com>

* update: 添加问题“2138.将字符串拆分为若干长度为k的组”的代码和题解(#994)

Signed-off-by: LetMeFly666 <814114971@qq.com>

---------

Signed-off-by: LetMeFly666 <814114971@qq.com>