update: 添加问题“2561.重排水果”的代码和题解 (#1060)
* 2561: WA.cpp (#1059)

* 2561: RE.cpp (#1059) - 爆int了

* 2561: AC.cpp (#1059)

* 2561: WA.py (#1059)

* 2561: AC.py (#1059)

cpp - AC,37.63%,96.77%
py - AC,62.59%,60.43%

* word(2561): WA.go (#1059)

不要被trae的自动补全所干扰

* word(2561): RE.go (#1059)

Line 31: Char 25: undefined: abs (solution.go)

* 2561: AC.go+CE.java (#1059)

go - AC,36.54%,26.25%

Line 17: error: method merge in interface Map<K,V> cannot be applied to given types;
            timeDiffs.merge(1, Integer::sum);
                     ^
  required: Integer,Integer,BiFunction<? super Integer,? super Integer,? extends Integer>
  found:    int,Integer::sum
  reason: actual and formal argument lists differ in length
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
Line 17: error: incompatible types: Integer is not a functional interface
            timeDiffs.merge(1, Integer::sum);
                               ^
Line 21: error: method merge in interface Map<K,V> cannot be applied to given types;
            timeDiffs.merge(-1, Integer::sum);
                     ^
  required: Integer,Integer,BiFunction<? super Integer,? super Integer,? extends Integer>
  found:    int,Integer::sum
  reason: actual and formal argument lists differ in length
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
Line 21: error: incompatible types: Integer is not a functional interface
            timeDiffs.merge(-1, Integer::sum);
                                ^
Line 39: error: method sort in interface List<E> cannot be applied to given types;
        change.sort();
              ^
  required: Comparator<? super Integer>
  found:    no arguments
  reason: actual and formal argument lists differ in length
  where E is a type-variable:
    E extends Object declared in interface List
5 errors

* 2561: AC.java (#1059) - 小憩一会儿

java - AC,94.93%,97.21%

* 2561: CE.rust (#1059)

* 2561: CE.rust (#1059)

困了说明，也太不走心了

* 2561: AC.rust (#1059)

rust - AC,34.69%,63.27%

* update: 添加问题“2561.重排水果”的代码和题解 (#1060)

Signed-off-by: LetMeFly666 <814114971@qq.com>

* typo: 哈哈 leetcode还干过这事儿呢 (#1059)

---------

Signed-off-by: LetMeFly666 <814114971@qq.com>