feat: subprocess test - windows上也会主程序立刻结束运行但5秒后文件被追加 (#1062)
If you are sure you want to delete it, run 'git branch -D dev'.
PS F:\OtherApps\Program\Git\Store\Store20_LeetCode> git push
fatal: The current branch 904 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin 904

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.

PS F:\OtherApps\Program\Git\Store\Store20_LeetCode> git push --set-upstream origin 904
Enumerating objects: 131, done.
Counting objects: 100% (127/127), done.
Delta compression using up to 8 threads
Compressing objects: 100% (91/91), done.
Writing objects: 100% (94/94), 70.89 KiB | 448.00 KiB/s, done.
Total 94 (delta 74), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (74/74), completed with 20 local objects.
To ssh.github.com:LetMeFly666/LeetCode
   9515dbdf8a1..48ec15d24fc  904 -> 904
branch '904' set up to track 'origin/904'.
PS F:\OtherApps\Program\Git\Store\Store20_LeetCode> git branch -d dev
warning: not deleting branch 'dev' that is not yet merged to
         'refs/remotes/origin/dev', even though it is merged to HEAD.
error: The branch 'dev' is not fully merged.
If you are sure you want to delete it, run 'git branch -D dev'.
PS F:\OtherApps\Program\Git\Store\Store20_LeetCode> git branch -D Dev
Deleted branch Dev (was b28f785b51d).
PS F:\OtherApps\Program\Git\Store\Store20_LeetCode>